### PR TITLE
error gracefully when `@main` is missing

### LINKED ISSUE #344: programs without `@main` crash Rust runtime and hang C runtime
This is what's currently causing tests to timeout on main; `tuples.hvm` is empty.

```
$ hvm run empty.hvm
thread 'main' panicked at src/main.rs:177:69:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
$ hvm run-c empty.hvm
[hangs]
```

### PR DESCRIPTION
**Pull request by tjjfvi**
Fixes #344

### CODE REVIEW

File: src/ast.rs [hunk 1]
```diff
@@ -505,18 +505,19 @@ impl Book {
...
-          rbag: vec![],
-          node: vec![],
-          vars: 0,
-        };
-        ast_def.build(&mut def, &name_to_fid, &mut BTreeMap::new());
-        book.defs.push(def);
-      }
+      let Some(ast_def) = self.defs.get(name) else {
+        panic!("missing `@main` definition");
+      };
```
Comment (enricozb) [inline src/ast.rs:510]: maybe just `expect` instead of `let .. else`?

**Review by enricozb — APPROVED** [review]
